image:
  repository: node
  tag: 18

cronJobs:
  - name: ingest-content
    schedule: "0 6 * * *" # every day at 6am UTC (1AM EST)
    command: ["npm", "run", "ingest:all"]
    env:
      OPENAI_EMBEDDING_MODEL: text-embedding-ada-002
      OPENAI_EMBEDDING_MODEL_VERSION: 2023-03-15-preview
      MONGODB_DATABASE_NAME: docs-chatbot-staging
      VECTOR_SEARCH_INDEX_NAME: default
      OPENAI_CHAT_COMPLETION_MODEL_VERSION: 2023-06-01-preview
    envSecrets:
      MONGODB_CONNECTION_URI: docs-chatbot-staging
      OPENAI_ENDPOINT: docs-chatbot-staging
      OPENAI_API_KEY: docs-chatbot-staging
      OPENAI_EMBEDDING_DEPLOYMENT: docs-chatbot-staging
      OPENAI_CHAT_COMPLETION_DEPLOYMENT: docs-chatbot-staging
      DEVCENTER_CONNECTION_URI: docs-chatbot-staging
      GITHUB_ACCESS_TOKEN: docs-chatbot-staging
      UNIVERSITY_DATA_API_KEY: docs-chatbot-staging
    resources:
      # guaranteed amount of resources
      requests:
        cpu: 100m
        memory: 2Gi
      # maximum allowed resources
      limits:
        cpu: 500m
        memory: 5Gi

# Alerts
defaultAlerts:
  enabled: true
  email: "chatbot-alerts@mongodb.com"
