service:
  targetPort: 3000

env:
  PORT: 3000
  OPENAI_EMBEDDING_MODEL: text-embedding-ada-002
  OPENAI_EMBEDDING_MODEL_VERSION: 2023-03-15-preview
  MONGODB_DATABASE_NAME: docs-chatbot-prod
  VECTOR_SEARCH_INDEX_NAME: default
  OPENAI_CHAT_COMPLETION_MODEL_VERSION: 2023-06-01-preview
  ALLOWED_ORIGINS: https://mongodb.com,https://www.mongodb.com
  NODE_ENV: production


envSecrets:
  MONGODB_CONNECTION_URI: docs-chatbot-prod
  OPENAI_ENDPOINT: docs-chatbot-prod
  OPENAI_API_KEY: docs-chatbot-prod
  OPENAI_EMBEDDING_DEPLOYMENT: docs-chatbot-prod
  OPENAI_CHAT_COMPLETION_DEPLOYMENT: docs-chatbot-prod

ingress:
  enabled: true
  hosts:
    - chat-server.docs.prod.corp.mongodb.com

resources:
  limits:
    memory: 1300Mi
  requests:
    memory: 1100Mi
# TODO: update this to do the elastic-beanstalky stuff
# need to define resource requests. see kanopy docs and https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#algorithm-details
# autoscaling:
#   minReplicas: 2
#   maxReplicas: 5
#   metrics:
#     - type: Resource
#       resource:
#         name: cpu
#         targetAverageUtilization: 80
