service:
  targetPort: 3000

env:
  PORT: 3000
  MONGODB_DB_NAME: docs_chat_staging

# TODO: add this via kubectl when database is created
# envSecrets:
#   MONGODB_CONNECTION_URI: chat-server-atlas-uri-staging

ingress:
  enabled: true
  hosts:
    - chat-server.docs.staging.corp.mongodb.com

resources:
  limits:
    memory: 1300Mi
  requests:
    memory: 1100Mi
